[package]
name = "instplot-lite"
version = "0.3.2"
edition = "2024"
description = "A lightweight native data plotting and point-editing tool"
license = "MIT"

[dependencies]
calamine = "0.36.1"
chardetng = "1.0.0"
csv = "1.4.0"
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
egui_plot = "0.37.0"
encoding_rs = "0.8.35"
fasteval2 = "2.1.1"
nalgebra = { version = "0.33.2", default-features = false, features = ["std"] }
png = "0.18.0"
rfd = "0.17.2"
rust_xlsxwriter = "0.99.0"

[target.'cfg(windows)'.dependencies]
ed25519-dalek = "3.0.0"
semver = "1.0.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
ureq = { version = "3.4.2", default-features = false, features = ["rustls", "gzip", "win-system-proxy"] }

[dev-dependencies]
ed25519-dalek = "3.0.0"
semver = "1.0.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
ureq = { version = "3.4.2", default-features = false, features = ["rustls", "gzip"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
